### ISSUE TITLE
Moodle 2.7.2 - user_picture() must be an instance of std class

### ISSUE THREAD

**Issue by eddt750** [netspotau/moodle-block_poll#3]
[14-Jan-2015 09:29:26 Europe/London] Default exception handler: Coding error detected, it must be fixed by a programmer: PHP catchable fatal error Debug: Argument 1 passed to core_renderer::user_picture() must be an instance of stdClass, boolean given, called in [dirroot]\blocks\poll\tab_responses.php on line 74 and defined
Error code: codingerror
- line 393 of \lib\setuplib.php: coding_exception thrown
- line 2262 of \lib\outputrenderers.php: call to default_error_handler()
- line 74 of \blocks\poll\tab_responses.php: call to core_renderer->user_picture()
- line 65 of \blocks\poll\tabs.php: call to include()

I bodged a fix which is basically to remove the call to the user picture, I'm sure someone with a clue what they're doing knows how to make it work correctly but this at least displays the responses:
line 74 tab_responses.php
$table->data[] = array_merge(array(fullname($user), userdate($response->submitted)),
                                block_poll_get_response_checks($options, $response->optionid));

Thanks,

Edd

**Comment by aolley** [comment]
Hi eddt750:

If $user is set to a boolean at that point, it must be because there's no user record matching the userid for the response.

I've added the following commit to have it simply not display responses from users that don't exist for any reason:
https://github.com/netspotau/moodle-block_poll/commit/8174832a1df673ccb396eec4f5c1a0855101c53f
